name: doan
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_iconly: ^1.0.2
  shimmer: ^3.0.0
  fancy_shimmer_image: ^2.0.3
  dynamic_height_grid_view: ^0.0.4
  card_swiper: ^3.0.1
  dio: ^5.4.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/image/bag/
    - asset/image/banner/
    - asset/image/profile/
